In [1]:
import pandas as pd

In [3]:
bus = pd.read_csv('t1.csv')

In [4]:
bus

     ID NAME DEPARTMENT
0  1001    A        CSE
1  1002    B        ICT
2  1003    C        BBA
3  1004    D        EEE
4  1005    E         PE
5  1006    F         ME

In [5]:
bus['NAME'][2]='Habiba'

C:\Users\Computer Hospital\AppData\Local\Temp\ipykernel_11860\923210630.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  bus['NAME'][2]='Habiba'

In [6]:
bus

     ID NAME DEPARTMENT
0  1001    A        CSE
1  1002    B        ICT
2  1003    C        BBA
3  1004    D        EEE
4  1005    E         PE
5  1006    F         ME

In [7]:
bus.loc[2,'NAME'] = 'Habiba'

In [8]:
bus

     ID    NAME DEPARTMENT
0  1001       A        CSE
1  1002       B        ICT
2  1003  Habiba        BBA
3  1004       D        EEE
4  1005       E         PE
5  1006       F         ME

In [9]:
bus.index = {'x','y','z','m','n'}

ValueError: Length mismatch: Expected axis has 6 elements, new values have 5 elements

In [11]:
bus.index = {'m','n','o','p','x','y'}

In [12]:
bus

     ID    NAME DEPARTMENT
p  1001       A        CSE
y  1002       B        ICT
x  1003  Habiba        BBA
o  1004       D        EEE
n  1005       E         PE
m  1006       F         ME