In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
t1 = pd.read_cvs('testing.cvs')

AttributeError: module 'pandas' has no attribute 'read_cvs'

In [4]:
t= pd.read_csv('testing.csv')

In [5]:
t

    ID Name  Cgpa City
0  101    X  4.00  ZZZ
1  102    Y  3.99  AAA
2  103    Z  3.80  CCC
3  104    M  3.98  BBB
4  105    N  4.00  OOO

In [6]:
t[0]["ID"]= 404

KeyError: 0

In [8]:
t["ID"][0]=909

C:\Users\Computer Hospital\AppData\Local\Temp\ipykernel_16056\2400972679.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  t["ID"][0]=909

In [9]:
t

    ID Name  Cgpa City
0  101    X  4.00  ZZZ
1  102    Y  3.99  AAA
2  103    Z  3.80  CCC
3  104    M  3.98  BBB
4  105    N  4.00  OOO

In [12]:
t["ID"] .iloc[0] = 909

C:\Users\Computer Hospital\AppData\Local\Temp\ipykernel_16056\3181323224.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  t["ID"] .iloc[0] = 909

In [13]:
t

    ID Name  Cgpa City
0  101    X  4.00  ZZZ
1  102    Y  3.99  AAA
2  103    Z  3.80  CCC
3  104    M  3.98  BBB
4  105    N  4.00  OOO

In [14]:
t.loc[0, "ID"] = 909

In [15]:
t

    ID Name  Cgpa City
0  909    X  4.00  ZZZ
1  102    Y  3.99  AAA
2  103    Z  3.80  CCC
3  104    M  3.98  BBB
4  105    N  4.00  OOO

In [16]:
type(t)

pandas.DataFrame

In [18]:
t1 = t

In [19]:
t1

    ID Name  Cgpa City
0  909    X  4.00  ZZZ
1  102    Y  3.99  AAA
2  103    Z  3.80  CCC
3  104    M  3.98  BBB
4  105    N  4.00  OOO

In [21]:
t2 = t.copy()

In [22]:
t2

    ID Name  Cgpa City
0  909    X  4.00  ZZZ
1  102    Y  3.99  AAA
2  103    Z  3.80  CCC
3  104    M  3.98  BBB
4  105    N  4.00  OOO

In [23]:
t2.iloc[2,1]= "Noushe"

In [24]:
t2

    ID    Name  Cgpa City
0  909       X  4.00  ZZZ
1  102       Y  3.99  AAA
2  103  Noushe  3.80  CCC
3  104       M  3.98  BBB
4  105       N  4.00  OOO

In [25]:
t2.head()

    ID    Name  Cgpa City
0  909       X  4.00  ZZZ
1  102       Y  3.99  AAA
2  103  Noushe  3.80  CCC
3  104       M  3.98  BBB
4  105       N  4.00  OOO

In [35]:
t2.columns = list("ABCD")

In [36]:
t2

     A       B     C    D
0  909       X  4.00  ZZZ
1  102       Y  3.99  AAA
2  103  Noushe  3.80  CCC
3  104       M  3.98  BBB
4  105       N  4.00  OOO

In [37]:
t2.columns = list(["Roll", "Student_Name", "Result", "Address"])

In [38]:
t2

   Roll Student_Name  Result Address
0   909            X    4.00     ZZZ
1   102            Y    3.99     AAA
2   103       Noushe    3.80     CCC
3   104            M    3.98     BBB
4   105            N    4.00     OOO

In [42]:
t2.loc[2,"Result"] = 4.00

In [43]:
t2

   Roll Student_Name  Result Address  (2, Result)
0   909            X    4.00     ZZZ          4.0
1   102            Y    3.99     AAA          4.0
2   103       Noushe    4.00     CCC          4.0
3   104            M    3.98     BBB          4.0
4   105            N    4.00     OOO          4.0

In [44]:
t2.loc[0,0] = 900

In [45]:
t2

   Roll Student_Name  Result Address  (2, Result)      0
0   909            X    4.00     ZZZ          4.0  900.0
1   102            Y    3.99     AAA          4.0    NaN
2   103       Noushe    4.00     CCC          4.0    NaN
3   104            M    3.98     BBB          4.0    NaN
4   105            N    4.00     OOO          4.0    NaN

In [47]:
t2

   Roll Student_Name  Result Address  (2, Result)      0
0   909            X    4.00     ZZZ          4.0  900.0
1   102            Y    3.99     AAA          4.0    NaN
2   103       Noushe    4.00     CCC          4.0    NaN
3   104            M    3.98     BBB          4.0    NaN
4   105            N    4.00     OOO          4.0    NaN

In [48]:
t2.drop("Address",axis=1)

   Roll Student_Name  Result  (2, Result)      0
0   909            X    4.00          4.0  900.0
1   102            Y    3.99          4.0    NaN
2   103       Noushe    4.00          4.0    NaN
3   104            M    3.98          4.0    NaN
4   105            N    4.00          4.0    NaN

In [48]:
t2.drop("Address",axis=1)

   Roll Student_Name  Result  (2, Result)      0
0   909            X    4.00          4.0  900.0
1   102            Y    3.99          4.0    NaN
2   103       Noushe    4.00          4.0    NaN
3   104            M    3.98          4.0    NaN
4   105            N    4.00          4.0    NaN

In [50]:
t2.loc[[1,2,3],["Roll","Student_Name"]]

   Roll Student_Name
1   102            Y
2   103       Noushe
3   104            M

In [51]:
t2

   Roll Student_Name  Result Address  (2, Result)      0
0   909            X    4.00     ZZZ          4.0  900.0
1   102            Y    3.99     AAA          4.0    NaN
2   103       Noushe    4.00     CCC          4.0    NaN
3   104            M    3.98     BBB          4.0    NaN
4   105            N    4.00     OOO          4.0    NaN

In [53]:
t2.loc[(t2["Result"]==4.00)]

   Roll Student_Name  Result Address  (2, Result)      0
0   909            X     4.0     ZZZ          4.0  900.0
2   103       Noushe     4.0     CCC          4.0    NaN
4   105            N     4.0     OOO          4.0    NaN

In [55]:
t2.loc[(t2["Result"]==4.00) & (t2["Address"]=="OOO")]

   Roll Student_Name  Result Address  (2, Result)   0
4   105            N     4.0     OOO          4.0 NaN

In [56]:
t2.iloc[0,2]

np.float64(4.0)

In [57]:
t2.reset_index()

   index  Roll Student_Name  Result Address  (2, Result)      0
0      0   909            X    4.00     ZZZ          4.0  900.0
1      1   102            Y    3.99     AAA          4.0    NaN
2      2   103       Noushe    4.00     CCC          4.0    NaN
3      3   104            M    3.98     BBB          4.0    NaN
4      4   105            N    4.00     OOO          4.0    NaN

In [58]:
t2.reset_index(drop = True , inplace = True)

In [59]:
t2

   Roll Student_Name  Result Address  (2, Result)      0
0   909            X    4.00     ZZZ          4.0  900.0
1   102            Y    3.99     AAA          4.0    NaN
2   103       Noushe    4.00     CCC          4.0    NaN
3   104            M    3.98     BBB          4.0    NaN
4   105            N    4.00     OOO          4.0    NaN

In [60]:
t2.drop(0,axis=1)

   Roll Student_Name  Result Address  (2, Result)
0   909            X    4.00     ZZZ          4.0
1   102            Y    3.99     AAA          4.0
2   103       Noushe    4.00     CCC          4.0
3   104            M    3.98     BBB          4.0
4   105            N    4.00     OOO          4.0

In [62]:
t2 = t2.drop((2, "Result"), axis=1)

In [63]:
t2

   Roll Student_Name  Result Address      0
0   909            X    4.00     ZZZ  900.0
1   102            Y    3.99     AAA    NaN
2   103       Noushe    4.00     CCC    NaN
3   104            M    3.98     BBB    NaN
4   105            N    4.00     OOO    NaN

In [64]:
t2["Roll"] = None

In [65]:
t2

   Roll Student_Name  Result Address      0
0  None            X    4.00     ZZZ  900.0
1  None            Y    3.99     AAA    NaN
2  None       Noushe    4.00     CCC    NaN
3  None            M    3.98     BBB    NaN
4  None            N    4.00     OOO    NaN

In [66]:
t2["Roll"].isnull()

0    True
1    True
2    True
3    True
4    True
Name: Roll, dtype: bool

In [67]:
t2.drop_duplicates(subset = ['Result'], keep= False)

   Roll Student_Name  Result Address   0
1  None            Y    3.99     AAA NaN
3  None            M    3.98     BBB NaN