In [1]:
import numpy as np

In [2]:
%pip install pandas

Requirement already satisfied: pandas in C:\Users\Computer Hospital\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Computer Hospital\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Computer Hospital\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Computer Hospital\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\Computer Hospital\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
dict1 = {
    "name":['Noushe','Ashrafia','Sumaiya','Nusrat'],
    "cgpa":[3.99,4.00,4.00,4.00],
    "ID":[29,1029,27,22]  
}

In [5]:
df = pd.DataFrame(dict1)

In [6]:
df

       name  cgpa    ID
0    Noushe  3.99    29
1  Ashrafia  4.00  1029
2   Sumaiya  4.00    27
3    Nusrat  4.00    22

In [7]:
df.to_csv('friends.csv')

In [8]:
df

       name  cgpa    ID
0    Noushe  3.99    29
1  Ashrafia  4.00  1029
2   Sumaiya  4.00    27
3    Nusrat  4.00    22

In [9]:
df.to_csv('friends_index_rmv.csv', index = False)

In [10]:
df

       name  cgpa    ID
0    Noushe  3.99    29
1  Ashrafia  4.00  1029
2   Sumaiya  4.00    27
3    Nusrat  4.00    22

In [11]:
df.head(2)

       name  cgpa    ID
0    Noushe  3.99    29
1  Ashrafia  4.00  1029

In [12]:
df.tail(1)

     name  cgpa  ID
3  Nusrat   4.0  22

In [13]:
df.describe()

         cgpa           ID
count  4.0000     4.000000
mean   3.9975   276.750000
std    0.0050   501.508641
min    3.9900    22.000000
25%    3.9975    25.750000
50%    4.0000    28.000000
75%    4.0000   279.000000
max    4.0000  1029.000000

In [14]:
import os

print(os.getcwd())

C:\Users\Computer Hospital\OneDrive\Desktop\NumPy

In [15]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'bus_info.xlsx',
 'friends.csv',
 'friends_index_rmv.csv',
 'Notes_to_readBefore.txt',
 'Pandas.ipynb',
 'PythonNotebook',
 'Second_tutorial.ipynb']

In [16]:
bus = pd.read_csv('bus_info.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'bus_info.csv'

In [ ]:
import os

In [ ]:
print(os.getcwd())

In [ ]:
print(os.listdir())

In [ ]:
bus = pd.read_csv('./bus_info.csv')

In [ ]:
bus = pd.read_excel('bus_info.xlsx')

In [ ]:
x = pd.read_csv('bus_info.xlsx')

In [ ]:
bus = pd.read_excel('bus_info.xlsx')

In [ ]:
bus = pd.read_csv('bus_info.csv')

In [ ]:
b = pd.read_csv('bus_info.xlxs')

In [ ]:
bus = pd.read_excel('bus_info.xlsx')

In [ ]:
%pip install openpyxl

In [17]:
bus = pd.read_excel('bus_info.xlsx')

In [18]:
bus

       Time  Bus Ticket
0  06:19:00  Aaa      x
1  05:30:00  BBb      y
2  06:50:00  CCc      z
3  07:00:00  DDd      m
4  09:00:00  Eee      n

In [19]:
bus['Bus']

0    Aaa
1    BBb
2    CCc
3    DDd
4    Eee
Name: Bus, dtype: str

In [23]:
bus.loc[2,'Bus']='FFf'

In [24]:
bus

       Time  Bus Ticket
0  06:19:00  Aaa      x
1  05:30:00  BBb      y
2  06:50:00  FFf      z
3  07:00:00  DDd      m
4  09:00:00  Eee      n

In [25]:
bus.to_csv('bus_info.xlxs')