In [1]:
import pandas as pd

In [2]:
ser = pd.Series(np.random.rand)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
ser = pd.Series(np.random.rand)

In [5]:
type(ser)

pandas.Series

In [6]:
newDataF = pd.DataFrame(np.random.rand(330,5), index =np.arange(330))

In [7]:
newDataF.head(0)

Empty DataFrame
Columns: [0, 1, 2, 3, 4]
Index: []

In [8]:
newDataF.head(2)

          0         1         2         3         4
0  0.475765  0.557253  0.723633  0.912709  0.886923
1  0.006812  0.504616  0.498677  0.925862  0.779716

In [10]:
newDataF.head()

          0         1         2         3         4
0  0.475765  0.557253  0.723633  0.912709  0.886923
1  0.006812  0.504616  0.498677  0.925862  0.779716
2  0.686799  0.211562  0.052495  0.735418  0.484548
3  0.234661  0.184920  0.867142  0.158938  0.003726
4  0.439743  0.874163  0.407880  0.936192  0.136068

In [11]:
newDataF

            0         1         2         3         4
0    0.475765  0.557253  0.723633  0.912709  0.886923
1    0.006812  0.504616  0.498677  0.925862  0.779716
2    0.686799  0.211562  0.052495  0.735418  0.484548
3    0.234661  0.184920  0.867142  0.158938  0.003726
4    0.439743  0.874163  0.407880  0.936192  0.136068
..        ...       ...       ...       ...       ...
325  0.395652  0.647752  0.770207  0.758268  0.511684
326  0.305650  0.447470  0.247323  0.173764  0.958249
327  0.179765  0.352583  0.860844  0.881015  0.388323
328  0.675199  0.893639  0.729081  0.148151  0.436233
329  0.704046  0.335197  0.177589  0.210163  0.374992

[330 rows x 5 columns]

In [12]:
type(newDataF)

pandas.DataFrame

In [13]:
newDataF.describe()

                0           1           2           3           4
count  330.000000  330.000000  330.000000  330.000000  330.000000
mean     0.505668    0.520555    0.496048    0.494470    0.510747
std      0.280219    0.293587    0.290121    0.285869    0.292561
min      0.000784    0.001987    0.001421    0.003765    0.001767
25%      0.275152    0.267542    0.256676    0.253341    0.259085
50%      0.496421    0.529288    0.498601    0.491886    0.508865
75%      0.757141    0.777535    0.746820    0.749588    0.769726
max      0.996536    0.993082    0.996827    0.990718    0.997764

In [14]:
newDataF.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [15]:
newDataF[0][0]='Noushe'

C:\Users\Computer Hospital\AppData\Local\Temp\ipykernel_10528\2364493783.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  newDataF[0][0]='Noushe'

TypeError: Invalid value 'Noushe' for dtype 'float64'

In [16]:
newDataF

            0         1         2         3         4
0    0.475765  0.557253  0.723633  0.912709  0.886923
1    0.006812  0.504616  0.498677  0.925862  0.779716
2    0.686799  0.211562  0.052495  0.735418  0.484548
3    0.234661  0.184920  0.867142  0.158938  0.003726
4    0.439743  0.874163  0.407880  0.936192  0.136068
..        ...       ...       ...       ...       ...
325  0.395652  0.647752  0.770207  0.758268  0.511684
326  0.305650  0.447470  0.247323  0.173764  0.958249
327  0.179765  0.352583  0.860844  0.881015  0.388323
328  0.675199  0.893639  0.729081  0.148151  0.436233
329  0.704046  0.335197  0.177589  0.210163  0.374992

[330 rows x 5 columns]

In [17]:
newDataF.head()

          0         1         2         3         4
0  0.475765  0.557253  0.723633  0.912709  0.886923
1  0.006812  0.504616  0.498677  0.925862  0.779716
2  0.686799  0.211562  0.052495  0.735418  0.484548
3  0.234661  0.184920  0.867142  0.158938  0.003726
4  0.439743  0.874163  0.407880  0.936192  0.136068

In [18]:
newDataF[0][0]="Noushe"

C:\Users\Computer Hospital\AppData\Local\Temp\ipykernel_10528\1209991683.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  newDataF[0][0]="Noushe"

TypeError: Invalid value 'Noushe' for dtype 'float64'

In [19]:
newDataF.iloc[0,0] = "Noushe"

TypeError: Invalid value 'Noushe' for dtype 'float64'